language: node_js
sudo: required
services:
- docker
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - IMAGE_NAME=jnahas/cosmos-ui
  - secure: FcuuN2lRM4FLPru/SwuqbHlKfcn3f3A01SewSQQYX8b8H6OoA732UUEC2GekVv/gu5vly7hOTJrUqZy0QGxhVIMfgZ49gmzQG6M0UZh9a8LlZyQmISEJ/4sSYFTSDql8PlJ4966XLDA0qhPdUB6YRZJIZ75RJhfZ22x4wFX4pIb9p5YgaK9TR0SW/BWJZMt0nDZiJg4iA91ko4Z9Kz7Zde7bnG5tRgG5Q+DBayWdGD7By1t/m69iNj8hQ5Dxx6qWvmozWAEhI0UM/a61elGvCPaebmYLzziYDM5npu3++HwAo5FX5yAzs0EVf8gn+WYlkP8oo2fAQDO9w4IhReE9WrfizD6oV/P0dDYt3i7vaEVymvnARFXRtaGfCZ8tVbRNVy/f3so+2FJwwKDjNC8qcJ5IftbQXNplxasCI/A7CyckFUoE8UCZ26Zw+GM7Q64cAnduUc3KGUIBuQyH8oEcSnNqTOgUY7VNcblVyVnZb7IS59HD7f9O4wzE3NkuFatcNOSDExBL8yKDA9PB2l0EILwClYhf18SUzNxt79kaACJCZpwqcXBgD+UZwvc2cpD1Pq6kB5dHTiww94uAEMGOBk9UPuQ7XP9O1l7mM+yopd+WrWaOOsLxWt76H/YZnv5AUBcuZ3yX3kQer0DIh7J5ErbnLifyq2SkW3+I47x2puk=
  - secure: qY18js489GMgb6m/OZz67lZDVcdtFnZYtTIUkBsS2e2WGMhGBgtTmfz5gau8Hv5xCyj4mujcIDz8MHQ8kcjtfznztWEBLCsJgZnwi0JiJ/kgTCRAm9R0DbSfhffeDhoV17KzijpYE5P/7sQD+Vg0MLQdEuIlH7uBvgU0PZUnEOyae0gx1oOjgdkB7rCG2IOObFKslosbShxAxyBvgsWhHHvDA5GuoDfZltEjxIPlMnkAgwOtIV+OMsBrwtbYbuTdFrDPiGvuzdSzaeHoWHqPR3kPd03dJ145BfTPU1c7S5bwBNakjeM7ZBj9iBgCNAkLCORn/aSfiA4bQuC3vYUUOKnCWJ2lS2Y+yOiprudNtf+eId5Xo9pdrc38gFEaF4dXPdaNMeB+TJHw8ztmY1jKxFTpImoYkBTEvWmFox2QdbJM2etojY51OB3r0UnZNOiPOcwZLys3jDEm8C188ZPFm1ceXyg83vkBqjsqDlrrJDjmgvN+c0IC87CyIGPQrTt3zfwQ+HdCxQvpFNO+pWnob6udYlwZ749smqls4s7hDskmb8PmB6+qM8k5gqGYBcK+xD7o+81N7iSvEfDkWd3cIXMjpVTyb4VbUte7yTVhiWYDMyeU41c6+LnmXzNDthkTWqWhIR+C3cPYn+sXDd39D0w21Tw1LVss4dV/mZUwY6I=
install:
- npm install
script:
- npm run build
- npm run test
- echo "Reporting coverage against $(node -v)..."
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t "$IMAGE_NAME":latest .
- docker push "$IMAGE_NAME"
