language: node_js
sudo: required
services:
- docker
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - IMAGE_NAME=jnahas/cosmos-ui
  - secure: FcuuN2lRM4FLPru/SwuqbHlKfcn3f3A01SewSQQYX8b8H6OoA732UUEC2GekVv/gu5vly7hOTJrUqZy0QGxhVIMfgZ49gmzQG6M0UZh9a8LlZyQmISEJ/4sSYFTSDql8PlJ4966XLDA0qhPdUB6YRZJIZ75RJhfZ22x4wFX4pIb9p5YgaK9TR0SW/BWJZMt0nDZiJg4iA91ko4Z9Kz7Zde7bnG5tRgG5Q+DBayWdGD7By1t/m69iNj8hQ5Dxx6qWvmozWAEhI0UM/a61elGvCPaebmYLzziYDM5npu3++HwAo5FX5yAzs0EVf8gn+WYlkP8oo2fAQDO9w4IhReE9WrfizD6oV/P0dDYt3i7vaEVymvnARFXRtaGfCZ8tVbRNVy/f3so+2FJwwKDjNC8qcJ5IftbQXNplxasCI/A7CyckFUoE8UCZ26Zw+GM7Q64cAnduUc3KGUIBuQyH8oEcSnNqTOgUY7VNcblVyVnZb7IS59HD7f9O4wzE3NkuFatcNOSDExBL8yKDA9PB2l0EILwClYhf18SUzNxt79kaACJCZpwqcXBgD+UZwvc2cpD1Pq6kB5dHTiww94uAEMGOBk9UPuQ7XP9O1l7mM+yopd+WrWaOOsLxWt76H/YZnv5AUBcuZ3yX3kQer0DIh7J5ErbnLifyq2SkW3+I47x2puk=
  - secure: qY18js489GMgb6m/OZz67lZDVcdtFnZYtTIUkBsS2e2WGMhGBgtTmfz5gau8Hv5xCyj4mujcIDz8MHQ8kcjtfznztWEBLCsJgZnwi0JiJ/kgTCRAm9R0DbSfhffeDhoV17KzijpYE5P/7sQD+Vg0MLQdEuIlH7uBvgU0PZUnEOyae0gx1oOjgdkB7rCG2IOObFKslosbShxAxyBvgsWhHHvDA5GuoDfZltEjxIPlMnkAgwOtIV+OMsBrwtbYbuTdFrDPiGvuzdSzaeHoWHqPR3kPd03dJ145BfTPU1c7S5bwBNakjeM7ZBj9iBgCNAkLCORn/aSfiA4bQuC3vYUUOKnCWJ2lS2Y+yOiprudNtf+eId5Xo9pdrc38gFEaF4dXPdaNMeB+TJHw8ztmY1jKxFTpImoYkBTEvWmFox2QdbJM2etojY51OB3r0UnZNOiPOcwZLys3jDEm8C188ZPFm1ceXyg83vkBqjsqDlrrJDjmgvN+c0IC87CyIGPQrTt3zfwQ+HdCxQvpFNO+pWnob6udYlwZ749smqls4s7hDskmb8PmB6+qM8k5gqGYBcK+xD7o+81N7iSvEfDkWd3cIXMjpVTyb4VbUte7yTVhiWYDMyeU41c6+LnmXzNDthkTWqWhIR+C3cPYn+sXDd39D0w21Tw1LVss4dV/mZUwY6I=
  - secure: HlPE4j+/TXS1eUiCiJjxa926XtWV5BtXruyeDlkMf2CY82vCZNG8smB4p2x1dCw7ac8QbvV0Rf/Aa94pgIdZrFp/kw2ZX1e8JwzMo0qG0JRxn2TF6+dtiWp4X2HrSmb8HcyCG4B33wzeWfmIIoauZ6/G8rlBr23AVT4edBJ30I368IPOuCOBdxerQMa7ScaqvwjmZVG2Rr/jq0iimGb0xfQOD2YaVpWTnXDTkSwIosTeQKMB3CJJYHgZmf0GvsuQuPrx7jfZN7reMgjwz+pFbRZer/W2LQeC7E9bm0Ccf4bMK2NmORjv1ifAGZdu8X91F3c4rrdi8+s30boPYLCna8OmWk0LGWhUp55Tb+Ja6Ck/BqQxmrziIsXbpiDKozGe1UhNmcEP0P4tew6rHULpdZXUvBbH6VZT47eMW2+ETvnBJT0mRSCISGLJfW6bCMigxU0QKyaXhcVM8W/e3R0PEktXFYo7HckOePlF/3C3d3scho8cKhY7mOnF0dKg0XI24lCmyPqw7MmcldqpT0i7XanmPB5FktutXRwM0ySqSYztgJaosnBIKBBIiQnC1rOvuM9/ozs61Gufi/AzDO9x5MGeuXcA/ObUTWNsUD/ia9U+i4WlqxsRBkN9DWWK4c2YKenpzT1VIMSWKpAfZLEjbDtq8fZesFsxufe4WzAo3xU=
  - secure: QAdc4NrqWut2IjWVE5ZBNXF3S1pdEomXppP35+4w7schduAS7PtEt+1o99898M5KNaM31Siwl6OL33cdJ1mhbjG4wKi4GITRJzLo9Yw38YsC/Mo8Zcd/ExVh6Gll5COFbUnQigu/I6XyohGdNGYzBQBqZygn8z+tY+jff2E5lBYykIfJ7BXeqLxwc+bAksUTWMIjjHlqkn3IKl0d+joKmooFvvcKcjs6WYh20QQSLLP7VIO1JxlxVXdfeTg1r5cEjBWU8EFdkgj/jT8IDpLTg2xOKaDqNk0L8akUxy6s+37qBgqyq6Aa3V3uJYdrs+UO++Hc9n5zECR8UvQ4aAw33AvqjdsNKtARtzS9IWq7xo02LKviL89mHK06stg5s2wew2g4sNUw75T1hFVuTiJKdd/M35Q/leZZGsPCzNZrhTtu/eocaNFzAnB0td4wIKJtitlMPUIzeoA5pQT8omVuBaTlQgXDLfki9bgCxXfnB/R/As65sCz5UBjvVewH2toLOP5PwUbDnU7h0aG5HoYzs+u8hf8QSA054B9lOd+21AaMZw+NH1wz1J0MezO+nGiIona/EYCk+OIKLjNfjbpWT4hIE5+gMlL/Eh1iA0OkoPkVIULb0zzWTsBJssdpRUK7A3kXSoUSd6fWSBp6txkQQu184WPG04TUtorBNGKD0Fg=
install:
- npm install
script:
- npm run build
- npm run test
- echo "Reporting coverage against $(node -v)..."
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t "$IMAGE_NAME":latest .
- docker push "$IMAGE_NAME"
