language: node_js
sudo: required
services:
- docker
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - IMAGE_NAME=jnahas/cosmos-ui
  - secure: eon/A70bC96/PCg33K3uH8VfDVVmVNYk9JQvmRB5bGHHYnjuF1MJfdQBYl7ngolrHbeTWFA05iVI7XT+cyox96XqzHhABhghiA9SAq6llAw0Bnz00d/ixohaDkH+51hdm136xG4e4ei0qjU6OOg3jmq1ISv2rDTshrTAU/LN/oxYziWp3sAL5aA7v39gs6ewcTU1ilfYJlXZUmWyk7bltMzMQpnUdLsaufSlfkTcuSogXywLgF5SJ2gWYbOtRG3HvnIzQ5g0L8hSWaC2+j2juNOWJrDXGR3d6Dr6AjQbrrA0B6z60Iq3Q9g9ZCwUVbBwHXoCuhuGzqUHULRxuFgOLrVPa97DkhZ3EWahisEiOq6BW5yaHqIUoO1gM9HVN1IC5K4QPpgvghCSW/r7SwNpq9ticWMKTjLCOqm2CebL0wK3fY3pDii4PuuuCBZse1gHTAV7sFs+OTzgkZ6KBdn7hykg1oM+bEKzmFJmcDRY/dZl1Ax48wY06WlTwaC84crrXRVCQwaY4Ob+9groheQGSwEqjiacvNhO0Dsodtb+u5IG/ZBUSTHiuFNpg3KEfkaO8RN7DOmIvmBnzdEYC5LuSJjiHJI776+tSwrKhlir9Hqzwlmyx/OOuvIRrBuPuUO/tpamdcjETNvFBf3Luq0q+dyEOaYoVJ2vlLCEsBgTVig=
  - secure: cjJezgnjZzGWZACaOE1aqhPTHeDc0fgxesf2D6VeBRcij2gSATZJ0X5CtPpdWixRuZIzoqmADqxPrjOcC5YKPCT7HKBDSgWIjE5jljGZzlTcGDzCQ/jgW57X23o+glfy6feXDaEZjuhQScTVW7+1ULdZHQzrOMKVHo8HgfneBHiHoQpdsRGoRo8p1nEK9dSKZkUVWCn8VgETjpJnmq7v5H2je5pAfB1tIycmqMM7aqMwnXSfm1VArxSZB34SELje1oIXHDbcLVo4Z5kA2uXWMMHe0deSF3WqA8mrNkQ4/4JONOkYVv+aizJ7gJTc2y48khC8+Bpvab9gDPmK/QKy+4bLXvdM0i2N3+yBxsG8lJebHkCBuTMxetMFEW9hkkm9bgfMrWjDXHYrj1M1yFseX3XNCZR4/FiXmbOpZk2iJXViRaUJWWMZEUF1DIx1GhGhxE9+jwsgVGp8IqIJahh1CyQJnqNL8vOkX1skJ/5MYt3EFUjt/XCJw/54bMt3DkOdUeOQrD6zlCZO0lAztq4se2U+axBLAcaGTUWpKmdcANYhnV40q9vdqoEzCBbVMLmBz9aaaOuKR4wUWvzhExd0mkiEBiWbAIUHIQ9QUTlG4kRONnUzDfEWSjEfj4gmpV4i5WJ64/l889aA5feGnT5FH5QdoEdVr4bowcU/vkOfnIM=
install:
- npm install
script:
- npm run build
- npm run test
- echo "Reporting coverage against $(node -v)..."
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t "$IMAGE_NAME":latest .
- docker push "$IMAGE_NAME"
