language: node_js
sudo: required
services:
- docker
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - IMAGE_NAME=jnahas/cosmos-ui
  - secure: bwcEy6Lg+/iH0+KWhg0JqDzwk5OPipHjnsmLrtWTT8eHkG/IbKv9ipZcHy6IqXeU98L2ssylWwcpW72sIzjzMd8OI7AjHtZCOb+UpKMocXur3KdRT+5TxPxQ2Mpf6eqwkYbHMpP7GfS1IZXv7oX5wyKAcqyJ7a9ShwXYk3DGzP62vu1zxLTu7icHKb4AECgXLXK/YFVwFh7WR1hw18VEQOKMoZpyjN7YyZKm49i2Ksd7zXQPNRaSTRlEUNnMfw73Ao+HVk2WQtAQ9RaOqMElo6V+MB36YQpaNkpyQg+69pviFKmXW5mZdpu6oInXgVTvz2DHYlL7bXWfvTIE1THpV6UnSF27nQ6Y/0L0L7MIIpAl9td15uUdOjL4Qyo3Pz7N24xn6g+1RD364IxiyY7rpQCLArMNjadKp2s0TVGaJ71tOq9Bp325sdOkEoLNYb0YcxVB5encdUqDFeMy106jBRtd2eMZxqG0hLSszrCMD8qG3oKbpnl5ew5RLlajbpiqrcoETy42Lco1gIRPuhSOkE3t+WXuB8UgBVJxYrgTEypIECWx+LfIJor5+nhai1rStYlK0MNQ8eNNv94qkw0mhM48iD3C1AHxGhLdsPddXvN4OvGTDZAYfSdj6Th9c9bdm9QAoNlpkHlo94w8hDMcQRgq9iCShTCYSzqimHsdwmw=
  - secure: BDVoq7xuwar8hptkD5xH3WN7GVmhfqk7w8kH+0wU3oFDh9D6TGBV3yF9vYsfqXHVzCGXyL59MSq63zWS74+pT8sT440o5y/WIJ+h0DCVjkOTd7ESn7T5yjVrxx6e4e+Lg1+qGTPMxi5TgA5IuJ3P/33A8kdX0vwPmX+iSck1sLFHe6lc/RUmth3vPvAOPOpOf2BDBXlKzZMHLM3SgF84TZsvu8rGzkPBc2SgyApMaYB7SpAvCiF8kYgeBlDhAZ7D5K395/sgb8pYw829Tzc3vEfEtzA03h4zRACFhvdCJSSx3BNILRrVsQjoNNFcx0NZ/vKULz7go0BikdIyI1C5Ht3yHylLe804i952/iYs3fuwCV2+sBoQvxnxFunFXIF5Ryr9hMOlhZeUl8Ul4SxuAclM715eT2EbObVHUZADkev3VhUWgalNZDF51qQVXm7h4xjGMqHQYAulFhrWQEBW37DciO6ZP/KtLydNI+9PI19aDnJ5YTWhHEu2dpgHpXA3d7opeQTO+AMqEz25FNDTUVj/jcDxOpZXzLmfH3Fr+Zh2tA4AM+BewoK5pzN2ZY/WoJbHHR27Rw73rOf27YQbkMnilC4PTSDpc22/FLfuxjF2ZzhYNdFUs0FC9rcgeJjCtCQxb3WzqRd7FBt/rltWqJTGNBlLwq709eX0nxpBzzI=
install:
- npm install
script:
- npm run build
- npm run test
- echo "Reporting coverage against $(node -v)..."
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t "$IMAGE_NAME":latest .
- docker push "$IMAGE_NAME"
