language: node_js
sudo: required
services:
- docker
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - IMAGE_NAME=jnahas/cosmos-ui
  - secure: qLq2NBVCME5a0CFXoxZkePJ/DGYiAh0tDElFGsLBhhFAFGc7SmYW6nTAOdu71m/Lp1LpECph61wlBwtWoUMF6CV6VJ6qu1ylST81jo8AfTseG4+HQFXE0zXD1ngWY72ZkJUnvKBnAYym/8wpsC1Xr5mcRnuVBJjZ7/P6BH6bZWMORp2ttv7r38J7QZYaS2KgHegR5ryl/p2vjAlgz93c0qn1ZAIzzB4n32ub9814aoipFPwjAL2yqzQjGXiTmXK9ErB6OgP8T+VmZ8z2X090RtwTL8cMZQi6wsVqaBnBdEXbET+hc/Em35GjWtDmhZ9NHcg/nF/Z7xxJ9Kc8DoxR8+pNLcISuji4Zi5lJBc5w2PR7wBEuDPryrce056Ndz7hhHHk1vNOGNqufZuEOM4gRFw0A7ZEQTiADiYalBLv3+TKtkRlluB/4e4/8uFlwfmUaCAVXu7svdhA9d4p19+9sMks5kNK+K7flBYHkWpe/S4NCFxWEn3l9qjREVyzvUy9iI14k0ROJwCh3HhtE0W3Gc7nIpU3LSkwKQuFmPHz0zc+xkcJpTIWyHmoA55vUwBd9i+lwqCuv92KQUTh/SUhfWfGV8DH/yNntQvpltL7Vd5hMGWFP3ig2vTPOIdR3rQUKh6c0lrxLC4MfPzeL5PoxPICLOr7QwC/7al23fwKynw=
  - secure: lNecCsrh6VlO/UWdzDUOqT5cdy3G2zQQ7p7mseZar4gsGIyK2wC9eLnVLun4Ed5PPV203xFlb0sbb5QjS6B4gEf1EbAR3gzZZ8FS8gC2L7+FPJO1EporQHCWboV4Rah3BfOCFLq7wOYMoQQvbQseJqg8cEuc8D743RigzxlfzyvIspmgotW8lOef70vL7CahWgcl8sSeleZjAG7IfOravuz3L3EmnhDd5MGGJBOZ4jfkRDbVfKD2wkeH/YvvsTnIXMHQw55FPM3N+ZwDLc3IQ9yoIHq2o0NP/P+8FAIc7Rk0rs58ZjiTSJ77hFgTfO9oO2bKhQqJGhOQambtUQnunGT/4/+NaHs17qFDfg0F0ZEP4SuYNuhbD6s6WAt9ROXIMP9hl2Xy+saaKzB+O2L9Q/Dk7/wBlf/IZJom18+5dIYqgjYUMCGVqcnIRitLrJyxhrgMrK5U23TOecSR/+kmCMbSVJ1e1585iHnfs0M1C3Um1uirD9EsnnL+QO8HYRxzkVhulH67b6eeFNv6Pii3OGschw7wAvt4j+nbJhTES1rCFKso9yiuylbNcchx3pM9YQ60ON0ielUpswy3Yb4xHPCMS2A/Zc9QGcCajd6QUN7ttCDKcwNbmCKGQAzx3faSLDYcJVayjQTWrjCUNdzR+zcRHl1tX1UjZ5kvAM2ScKI=
install:
- npm install
script:
- npm run build
- npm run test
- echo "Reporting coverage against $(node -v)..."
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker build -f Dockerfile -t "$IMAGE_NAME":latest .
- docker push "$IMAGE_NAME"
