language: node_js
sudo: required
services:
- docker
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - IMAGE_NAME=jnahas/cosmos-ui
  - secure: AVKKp7pPXRZhT45IOcB67dv+Sogv33WG3zIlNiNbWXVtA5SHwrwIEqmK8S7DwRSj/SL4uvkWSKSNW0HijcPCGse//WxV3O8VMQ2P81XpaQhrOHpi3zsmyXffksMGhPod+5kiCDlIU9q2/UTk3gldj5mlp+tJqYyWHATt/VQxJ92eucWqkkAMljzJuOMtI3d+DT0drp3JX44Vn+84OrsAV78381rWJ6jTzv2xWYinUT1jlqz2bj9KG5YRq6+WvZ9Hz65TvECoHHpdDNYiDnpBPLkBl+2oz6Xn14h7gx/OdWmuYulW57rYHL6+iUvBT6SnbPwCs66XaaY7tvpFxxypJOrDux/1/E6JO55nSCjnhPOAgrvu1dM2Iw53I5CgE7sZJMpF/fkPDMF+uWI/hXtSDSPJ+iOzVG/XGmXyYPtlzg1s2TB7rfejq3Z/oOsFI/SmP62Pi7YsRQXvXnpN0OKnF6wZVUXqo6vHCLwTowjQSbzKc2zKELGm7S3yP3NG+afanbfRDtWXcM6WounF8pjEQLS/QWEkhYnTF6wk+YaUvDsvrKR9OVPckQRNL6RrUtl0E1Mw0ZpSoDG8K8p7f0kLwFosNwuzE5fWTGe/7TFasosMJntvi1Q9F8tQnGpX0nn0fyRxhbC8I9SzbWM47KOVj55XQpMwZVifftMVWR8lc5I=
  - secure: c+ouZGVsKN/wVzS9l52pu71YwJISAeALlUBq/5rFFRYmIj0OXCChNcMwRiCbYQbTMAxV6VnjygNnmtgFKqtb9a3o/iu59lBjWZJ5cJV1F4DURc2WB9SlcAHGFuRsmYUPEB6iS8gWjnyocwcIokUV2xWkmVbf/xVq92oMsBKfEUedi0FBeIEOx6EVfr0DNWhXRPQT0Tw9xK1/tsaIHeA6Gzj/T0n2hBu8X0ULpJ1ghRHknzhtU1/IIxYAwWQZVfO+WaQQvPDtx41CW8G2fU0udyQj6FJvtgytgdmCI2Se3bIcgYF1GA1VLDAQPmGyM0BUG4eY9GA6TO2JP9L/67bvrdlUluM9tjM+gI+q2okUvuWN5k5sNho6J8rVUGpgJ7wREEkukBq+jAmuGhUn2RIwEJO5WIdxVeTAX8/qUJwwR3b5LKDzIq/ps5KDcQslMET/DS91+H36sDjMC5d8lA34nSdbS4OZ4G7z7mQfWZLsqwKELhfsMbNdBTdGi9W2qqDS2mD1ad4+h++qJh1ZW8USAvabKG9BkqFZ7O3u1MQ/UYn3CF2Ed0r0zblyS3cKRREw46B5wMlWTZa2jpF2q++YGSYz0idBs/iEVh1wW7VH3vyi/nb6l5j9bK1gX2du+OKEz9yB/xOMOrLWYSF8k0gnp1AiJ3EbhdpEB5fUOc8sgJE=
install:
- npm install
script:
- npm run build
- npm run test
- echo "Reporting coverage against $(node -v)..."
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t "$IMAGE_NAME":latest .
- docker push "$IMAGE_NAME"
