language: node_js
sudo: required

services:
  - docker

node_js:
- stable

cache:
  directories:
    - "node_modules"

env:
  global:
    - IMAGE_NAME=jnahas/cosmos-ui
    - secure: "HeB6iPE6CJo+QCuxX5UiR2a6yaDdcsEJJH3kuWAbyMylmbU4znCguGfZALhgcZpwgmB56swBaedJ4cT9tJmk0FvyPTs3tme8lOexrppsZ//Aqaz19ksBw6WiHugJQYZEv3rWJbMTS1JaK4q7uFaT7BnfafZx++lquR/IW/ESnEDGMssdQubmPWUVqwHOeff0tE1c2PMYz4kjG0IPnlp948SYYKKYD6rF6ZigTK1FrbSeFOT+ZKmkUczTVVFuNrqqPRILya1VD6LfKRsDSGCasgmUYup1/Unv/LwwTQGJLwuOO5jxCV6GCy0HtaWVWPuxsL/X7n/qpWygPDTeLCob6N1KLaiV0OVl8rQN8Ho8ogEgDbcOOYRoi/A7L1WV8IQsq1ymR0waDDUW9jSpyr6C5zGKw5KZftKrGTiGH5feFfKJE9yQ0W/sG+C6wFQpyYhItRr0+QnLZ+xHr38h2AU6HdLLzOB4sG3TtCkk9FspgAA3+mD4/CVyMEd8AB7Mt3nume9PvPbYCqju4a4Zc+2DELUGzw/PHH2uThQIUnC2sXmaJmacVT3BSS5GJldnmx7S8KNJ5nq44N6v1i+jB6tIUx5nl8UDwFQslKC7287MNEp9LfNK1u6Bm11FWrxz3AcPCuSnf6qam+DJYYB6y7bfYQYWGQO13wzAEb8dv1PVKa8="
    - secure: "bXiufyTktSjO3oGHSOjaGf+t40DmeFU1mkNXO4BDUnC89kNo0Dbw3lGXOI4j/Twc9jGwNCwu74/xzYyvVfaJTyD0AxcICmeZT8NFWwOEGZBYPOa0tu3kU0rCHXVAk7efDESPYVUBKYh/YLg51ypDwQV5DS967+Lk0Rg83GZe0lekBr17gZTGIB7hMfZGzgiM8zZNuSvYS1le/HFP6oO41qJzsuA2YpXZbnpm0k1pQrLBB5RcchDqPeamxGMHPjSRakuMt4uzshDoLQ8PgOHQdMNTwvV3E0joFNqXPbcpJLyPObvtT4YdksVr98DUzbD3cmGoCaVf4wtfcbXxJHhFzMfc4MtSS0MGRc7et3Id8G6fYLN5fbd1TC5Sx6brPG2V63GbuAXcQv+TWCCW26PXhnD7HvvvQA62Yfz/o7xKN3aKhhWUcoZ4hcTqPulhTScky+7ybj9+6oXovss7CEM17qzK0o3fHZYKuDG44yMi9mzf8+yS5kVunTEXWBJalv0izE2cRbVP9Q7cJRAJHzKMlmP75ZKDN+7duC0q3qNXI1IYT7Igg3NFbhovH3tG2wv89PCa8Y3uDlBDeFZA1DfCkDPfWMphCsJCAIWtaGLhEKqmmduoyrqA66li36rqGilHeP74Q3qDNXe8eVUHGZSpxdovL3l2AiVrbQvbsT5L6L8="
    - secure: "SZBsoH67My4PG96ujR/HCSqGDVnv7Y4o9GSvlTXgSlKjuFVW+W4nhP6EJ7sd1mJkyW8KQSWRrn2Ee3fJqQUbgwgRtHk2EQAkRRxF5aeUbGpP+/qusY9hfxhKDaSW8hGJb+K6O/n1H6+ty4ZTf0/vy3ldBvx6dOOoiqgtvkaleYvD0IumIJv3RgL4PlcktUDBgTSelbMzLvSlIgq1QRipHXfRAM399fSbxRXX5Ht15ftDqgj+udXBjn5g+K2AYW+C6bc0RemG9tPiTC/eKiUlYaLij2KuXQbirHDKS4tiGo0huUVNZr8io9OMXvvfK4F19P2i4Mt2FrELW7kRNItm8egPJT1/+b9Jl43v4cc6QmjPY4EEqgQ7WXsR4qLig09hqIrMjh97ztvQEiatHJTClt704kqr0MQHZrWkBCI9rmSCw0bTbzfYckUayfY9BoQU3WkJg3h/X2eROVo1TGuZPK9f/s70tJzvSBS1jDPymcEW9waP7LhVzGnBFFedenMI4WWvWA5CnkwLFmyTMal3gOax9LaH3/b4/vyMryqDSWJ/E1/j7e0sRPapVx8NzyH9GGmTsDF7kODDUrHbDnhaOIAGJDb12lHNQNLRPEfcWERrcSJkiV/Vp9W2/gEq8t6P7QiZMcsz1dm6Jv5nAc3wdKB9rpIobsHYv6KnMHn4Vi8="
        
install:
- npm install

script:
# need to run npm test, when present
- npm run build

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=jnahas/cosmos-ui
  - docker build -f Dockerfile -t $IMAGE_NAME:latest .
  - docker push $IMAGE_NAME
